#Theme theme: jekyll-theme-cayman

# Site title
title: Interesting Stuff
description: A collection of interesting stuff related to my work

#
url: "https://marcovolino.github.io/interesting-papers"

#permalinks
permalink: pretty

# Handling Reading
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Use this for production
sass:
    style: compressed
exclude: [ README.md, LICENSE]


# Collection Management
collections_dir: collections
collections:
  papers:
    output: true
    permalink: /:collection/:name
